anguage: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install --optimize-autoloader --prefer-source

script:
  - vendor/bin/phpunit --verbose